add_newline = false
# A minimal left prompt
format = """$character$directory"""
# move the rest of the prompt to the right
right_format = """$all"""
command_timeout = 1000

[git_branch]
symbol = ""
format = '[[ $symbol $branch ](fg:#ff9e64)]($style)'

[git_status]
format = '[[($all_status$ahead_behind )](fg:#ff9e64)]($style)'

[nodejs]
symbol = ""
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[bun]
symbol = "B"
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[java]
symbol = " "
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[rust]
symbol = ""
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[golang]
symbol = ""
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[php]
symbol = ""
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[c]
symbol = " "
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[lua]
symbol = " "
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[python]
symbol = " "
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[docker_context]
symbol = " "
format = '[[ $symbol( $context) ](fg:#c3e88d)]($style)'

[character]
disabled = false
success_symbol = '[](bold fg:#4fd6be)'
error_symbol = '[](bold fg:#c53b53)'
vimcmd_symbol = '[](bold fg:#4fd6be)'
vimcmd_replace_one_symbol = '[](bold fg:#9d7cd8)'
vimcmd_replace_symbol = '[](bold fg:#9d7cd8)'
vimcmd_visual_symbol = '[](bold fg:#ffc777)'
