add_newline = false
# A minimal left prompt
format = """$character$directory"""
# move the rest of the prompt to the right
right_format = """$all"""
command_timeout = 1000

[git_branch]
symbol = " "
format = '[[ $symbol $branch ](fg:#957FB8)]($style)'

[git_status]
format = '[[($all_status$ahead_behind )](fg:#957FB8)]($style)'

[nodejs]
symbol = " "
format = '[[ $symbol ($version) ](fg:#7E9CD8)]($style)'

[bun]
symbol = "B"
format = '[[ $symbol ($version) ](fg:#7E9CD8)]($style)'

[java]
symbol = " "
format = '[[ $symbol ($version) ](fg:#7E9CD8)]($style)'

[rust]
symbol = " "
format = '[[ $symbol ($version) ](fg:#7E9CD8)]($style)'

[golang]
symbol = " "
format = '[[ $symbol ($version) ](fg:#7E9CD8)]($style)'

[php]
symbol = " "
format = '[[ $symbol ($version) ](fg:#7E9CD8)]($style)'

[c]
symbol = " "
format = '[[ $symbol ($version) ](fg:#7E9CD8)]($style)'

[lua]
symbol = " "
format = '[[ $symbol ($version) ](fg:#7E9CD8)]($style)'

[python]
symbol = " "
format = '[[ $symbol ($version) ](fg:#7E9CD8)]($style)'

[docker_context]
symbol = " "
format = '[[ $symbol( $context) ](fg:#98BB6C)]($style)'

[character]
disabled = false
success_symbol = '[ ](bold fg:#DDD8BB)'
error_symbol = '[ ](bold fg:#e82424)'
vimcmd_symbol = '[ ](bold fg:#c8c093)'
vimcmd_replace_one_symbol = '[ ](bold fg:#658594)'
vimcmd_replace_symbol = '[ ](bold fg:#658594)'
vimcmd_visual_symbol = '[ ](bold fg:#938aa9)'


[directory]
format = "[$path ](bold fg:#F1C982)"
truncation_length = 1

